services:
  - type: web
    name: your-app-name # Replace with your app name
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name # Replace with your database name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: your-database-name # Replace with your database name
    databaseName: your-database-name # Replace with your database name
    user: your-user-name # Replace with your user name
